/*
* generated by Xtext
*/
package fr.nantes.univ.alma.mvc.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class LanguageProposalProvider extends fr.nantes.univ.alma.mvc.ui.contentassist.AbstractLanguageProposalProvider {

}
