/*
 * generated by Xtext
 */
package fr.nantes.univ.alma.mvc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LanguageUiModule extends fr.nantes.univ.alma.mvc.ui.AbstractLanguageUiModule {
	public LanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
