/*
* generated by Xtext
*/
package fr.nantes.univ.alma.mvc.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
