/**
 * generated by Xtext
 */
package fr.nantes.univ.alma.mvc.ui.contentassist;

import fr.nantes.univ.alma.mvc.ui.contentassist.AbstractLanguageProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class LanguageProposalProvider extends AbstractLanguageProposalProvider {
}
