/*
* generated by Xtext
*/
package fr.nantes.univ.alma.mvc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("fr/nantes/univ/alma/mvc/parser/antlr/internal/InternalLanguage.tokens");
	}
}
